@startuml
skinparam actorStyle awesome
!theme plain
left to right direction

:User: as user
:Seller: as seller

user -> (Frontend)

(Frontend) -d-> Product
(Frontend) -d-> Basket
(Frontend) -d-> User

seller -> (Frontend)

package User {
  (Sign up)
  (Login)
}

package Product {
  (Add product)
  (Get product)
  (Update product)
  (List product)

  package Order {
    (List orders)
    (Make order)
    (Close order)
  }
}

package Basket {
  (Add to basket)
  (Checkout)
  (Cancel)
}

@enduml